name: PUBLISH

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter publish version, eg: 0.0.1'
        required: false

jobs:
  prepare:
    name: Prepare publish version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: master

      - name: Validate version
        id: validate-version
        run: |
          current_version=$(grep -m1 'version =' gradle.properties | grep -oE '([0-9]+\.[0-9]+\.[0-9]+)')
          input_version=${{ github.event.inputs.version }}
          echo "Current version: ${current_version}, Input version: ${input_version}"
          if ! [[ "${input_version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ERROR: Invalid version number ${input_version}. Please use format x.y.z"
            exit 1
          fi
          echo "publish_version=${input_version}" >> "${GITHUB_ENV}"
          echo "Publish version: ${input_version}"

      - name: Check tag existence
        run: |
          if ! [ $(git tag -l v"${{ env.publish_version }}") ]; then
            echo "ERROR: Tag v${{ env.publish_version }} does not exist"
            exit 1
          fi

      - name: Write version to file
        run: |
          echo "${publish_version}" >> /tmp/publish_version

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${GITHUB_SHA}
          path: /tmp/publish_version
          retention-days: 30

  publish:
    name: Publish
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: Download publish_version
        uses: actions/download-artifact@v7
        with:
          name: ${GITHUB_SHA}
          path: /tmp

      - name: Read publish version
        run: |
          publish_version=$(cat /tmp/publish_version)
          echo "publish_version=${publish_version}" >> "${GITHUB_ENV}"
          echo "Publish version: ${publish_version}"

      - name: Checkout publish tag
        uses: actions/checkout@v6
        with:
          ref: refs/tags/v${{ env.publish_version }}

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Build and publish
        run: ./gradlew publish -Dorg.gradle.parallel=false --info
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          NEXUS_REPO_PASSWORD: ${{ secrets.NEXUS_REPO_PASSWORD }}
          NEXUS_REPO_USERNAME: ${{ secrets.NEXUS_REPO_USERNAME }}
